services:

  database:
    env_file:
      - database.env

  sso:
    env_file:
      - sso/_.env

  api:
    env_file:
      - core.env
  
  worker_primary:
    env_file:
      - core.env

  worker_secondary:
    env_file:
      - core.env

  flower:
    env_file:
      - core.env

  beat:
    env_file:
      - core.env

  front:
    env_file:
      - front.env
