services:

  database:
    env_file:
      - database.dev.env

  sso:
    env_file:
      - sso/_.dev.env

  proxy:
    build: ./proxy
    env_file:
      - proxy/_.env
    ports:
      - 127.0.0.1:2222-2244:2222

  api:
    env_file:
      - core.dev.env
    volumes:
      - /var/lib/libvirt:/var/lib/libvirt

  worker_primary:
    env_file:
      - core.dev.env
    volumes:
      - docker_storage:/mnt/docker_storage
      - /var/lib/libvirt:/var/lib/libvirt

  worker_secondary:
    env_file:
      - core.dev.env
    volumes:
      - docker_storage:/mnt/docker_storage
      - /var/lib/libvirt:/var/lib/libvirt
  
  flower:
    env_file:
      - core.dev.env
  
  beat:
    env_file:
      - core.dev.env

  front:
    build:
      dockerfile: dev.Dockerfile
    env_file:
      - front.dev.env

volumes:
  docker_storage:
