services:

  setup:
    volumes:
      - ./setup/src:/app/src:ro
  api:
    build: ../src/core
    volumes:
      - ../src/core:/app/src

  worker_primary:
    build: ../src/core
    volumes:
      - ../src/core:/app/src

  worker_secondary:
    build: ../src/core
    volumes:
      - ../src/core:/app/src

  flower:
    build: ../src/core
    volumes:
      - ../src/core:/app/src

  beat:
    build: ../src/core
    volumes:
      - ../src/core:/app/src

  front:
    build:
      context: ../src/ui
    volumes:
      - ../src/ui/src:/app/src
