services:
  api:
    image: dimsicloud/backroll:$BACKROLL_VERSION

  worker_primary:
    image: dimsicloud/backroll:$BACKROLL_VERSION

  worker_secondary:
    image: dimsicloud/backroll:$BACKROLL_VERSION

  flower:
    image: dimsicloud/backroll:$BACKROLL_VERSION

  beat:
    image: dimsicloud/backroll:$BACKROLL_VERSION

  front:
    image: dimsicloud/backroll-ui:$BACKROLL_VERSION
    # TODO Update.
    ports:
      - 80:80
