name: ${BACKROLL_HOST_USER}_backroll-$BACKROLL_MODE

services:

  database:
    profiles:
      - database
    image: mariadb:10.3
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
    volumes:
      - ./database/@${BACKROLL_MODE}_persistence:/var/lib/mysql

  redis:
    image: redis:7.2
    command: "redis-server"

  sso:
    build:
      context: ./sso
      args:
        - BACKROLL_MODE=$BACKROLL_MODE
    profiles:
      - sso
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"

  api:
    command: bash commands/docker.sh api
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
    volumes:
      - ./core/@${BACKROLL_MODE}_persistence:/var/lib/backroll
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt
    depends_on:
      redis:
        condition: service_started
    # database:
    #   condition: service_healthy
    restart: on-failure # Compensates for the lack of database healthcheck.

  worker_primary:
    depends_on:
      - api
    command: bash commands/docker.sh worker_one
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
    volumes:
      - ./core/@${BACKROLL_MODE}_persistence:/var/lib/backroll
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt

  worker_secondary:
    depends_on:
      - worker_primary
    command: bash commands/docker.sh worker_two
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
    volumes:
      - ./core/@${BACKROLL_MODE}_persistence:/var/lib/backroll
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt

  flower:
    depends_on:
      - worker_primary
    command: bash commands/docker.sh flower
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
    volumes:
      - ./flower/@${BACKROLL_MODE}_persistence:/root/flower

  beat:
    depends_on:
      - worker_secondary
    command: bash commands/docker.sh beat
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"

  front:
    depends_on:
      - api
    env_file:
      - .env
      - "@$BACKROLL_MODE.env"
  
  server:
    image: nginx
    volumes:
      - ../src/server/containers.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - 80:80
    depends_on:
      api:
        condition: service_started
      front:
        condition: service_started
    restart: on-failure # Compensates for the lack of api and front healthcheck.
