# The user can override this default name with the “-p” option.
name: ${USERNAME:-${USER:-someone}}_backroll-$BACKROLL_MODE

services:

  database:
    profiles:
      - database
    image: mariadb:10.3
    env_file:
      - database/@$BACKROLL_MODE.env
    volumes:
      - ./database/@${BACKROLL_MODE}_persistence:/var/lib/mysql

  redis:
    image: redis:7.2
    command: "redis-server"

  setup:
    environment:
      # Suppress warnings with ${VAR:-}.
      - USER=${USER:-}
      - USERNAME=${USERNAME:-}
      - BACKROLL_MODE=$BACKROLL_MODE
    volumes:
      - .:/app/compose_project

  sso:
    profiles:
      - sso
    env_file:
      - sso/@$BACKROLL_MODE.env

  api:
    depends_on:
      redis:
        condition: service_started
      setup:
        condition: service_completed_successfully
      # database:
      #   condition: service_healthy
    restart: on-failure # Compensates for the lack of database healthcheck.
    command: bash api.command.sh
    env_file:
      - core/@$BACKROLL_MODE.env
    volumes:
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt

  worker_primary:
    depends_on:
      - api
    command: bash worker_primary.command.sh
    env_file:
      - core/@$BACKROLL_MODE.env
    volumes:
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt

  worker_secondary:
    depends_on:
      - worker_primary
    command: bash worker_secondary.command.sh
    env_file:
      - core/@$BACKROLL_MODE.env
    volumes:
      - ./core/ssh/@$BACKROLL_MODE:/root/shared_ssh
      - /mnt:/mnt

  flower:
    depends_on:
      - worker_primary
    command: celery -A app.celery flower --conf=flowerconfig.py --loglevel=info
    env_file:
      - core/@$BACKROLL_MODE.env
    volumes:
      - ./flower/@${BACKROLL_MODE}_persistence:/root/flower

  beat:
    depends_on:
      - worker_secondary
    command: celery -A app.celery beat -S redbeat.RedBeatScheduler --loglevel=info
    env_file:
      - core/@$BACKROLL_MODE.env

  front:
    depends_on:
      - api
    env_file:
      - front/@$BACKROLL_MODE.env
