services:

  database:
    env_file:
      - database.env

  sso:
    env_file:
      - sso/_.env
    ports:
      - 8081:8080
      - 9990:9990

  api:
    env_file:
      - core.env
    ports:
      - 5050:5050
  
  worker_primary:
    env_file:
      - core.env

  worker_secondary:
    env_file:
      - core.env

  flower:
    env_file:
      - core.env

  beat:
    env_file:
      - core.env

  front:
    env_file:
      - front.env
    ports:
      - 8080:80
