services:

  proxy:
    build: ./proxy
    env_file:
      - proxy/_.env
    ports:
      - 127.0.0.1:2222-2244:2222

  worker_primary:
    volumes:
      - docker_storage:/mnt/docker_storage

  worker_secondary:
    volumes:
      - docker_storage:/mnt/docker_storage

  front:
    build:
      dockerfile: dev.Dockerfile

volumes:
  docker_storage:
