cat <<HEREDOC
DEFAULT_USER_NAME=admin
DEFAULT_USER_PASSWORD=admin

FLOWER_PASSWORD=
FLOWER_USER=

FRONT_URL=

OPENID_CLIENT_API_ID=backroll-api
OPENID_CLIENT_API_SECRET=
OPENID_CLIENT_UI_ID=backroll-front
OPENID_ISSUER=
OPENID_REALM=backroll
HEREDOC
