# Makes the quickstart script targeting the current release.
# The current commit must be the current release.

tag_name=$(git describe --tags --exact-match) && \
cat <<HEREDOC > quickstart.sh
# Generated by make_quickstart.sh for tag “$tag_name”.
# Intented to be run with the bash source command.
# Do not use “set -e” because it will exit the user shell.

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "You must be outside a git repository." >&2
    return 1
fi

git clone --single-branch --branch "$tag_name" https://github.com/DIMSI-IS/backroll.git BackROLL && \\
cd BackROLL && \\
cd compose_project && \\
source source-me.sh setup-prod && \\
docker compose \$prod up
HEREDOC
