name: backroll # you probably want to 'snapcraft register <name>'
base: core24
version: "0.1"
summary: Backup and restore your KVM VMs # 79 char long summary
description: |
  Manage and schedule backups of your KVM or Apache CloudStack VMs in a web UI.
  Monitor the backups tasks, get notified on success or failure and restore as needed.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  redis:
    command: usr/bin/redis-server
    daemon: simple
    restart-condition: always

  api:
    command: app/commands/snap.sh api
    daemon: simple
    restart-condition: always
    plugs:
      - mnt

  worker-one:
    command: app/commands/snap.sh worker_one
    daemon: simple
    restart-condition: always
    plugs:
      - mnt

  worker-two:
    command: app/commands/snap.sh worker_two
    daemon: simple
    restart-condition: always
    plugs:
      - mnt

  beat:
    command: app/commands/snap.sh beat
    daemon: simple
    restart-condition: always

  flower:
    command: app/commands/snap.sh flower
    daemon: simple
    restart-condition: always

  ui:
    # Do not use “"”: app commands must consist of only alphanumeric characters, spaces, and the following characters: / . _ # : $ -
    command: app/commands/snap.sh ui $SNAP/app/ui $SNAP_DATA/usr/share/nginx/html
    daemon: simple
    restart-condition: always

parts:
  redis:
    plugin: nil
    stage-snaps:
      - redis

  core-python:
    source: src/core/python_project
    build-packages:
      - pkg-config
      - libssl-dev
      - liblz4-dev
      - libzstd-dev
      - libxxhash-dev
      - libacl1-dev
      - libvirt-dev
    stage-packages:
      - libvirt-dev
      - qemu-utils
    plugin: python
    python-requirements:
      - requirements.txt

  core-dump:
    source: src/core
    plugin: dump
    organize:
      commands: app/commands
      python_project/flower_config.py: app/flower_config.py
    stage:
      - app

  ui:
    plugin: nil
    source: src/ui
    build-packages:
      - nodejs
      - npm
    override-build: |
      export NODE_OPTIONS=--openssl-legacy-provider
      npm install --legacy-peer-deps
      npm run build

      src=dist
      dst="$SNAPCRAFT_PART_INSTALL/app/ui/"
      mkdir -p "$dst"
      cp -r "$src"/* "$dst"/

      cp nginx.conf "$SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ui.conf"
    stage-packages:
      - gettext
      - nginx

  ui-dump:
    source: src/ui
    plugin: dump
    # The dump plugin organize section does not support environment variables.
    organize:
      entrypoint.sh: app/commands/ui.sh
    stage:
      - app

  server:
    plugin: nil
    source: src/server
    # The dump plugin organize section does not support environment variables.
    override-build: |
      cp localhost.conf "$SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/server.conf"
    stage-packages:
      - nginx

  snap-src:
    source: snap_project
    plugin: dump
    organize:
      src: app
    stage:
      - app

# Binding must start with $SNAP, $SNAP_DATA or $SNAP_COMMON.
layout:
  /etc/nginx:
    # Configuration was placed here during build.
    bind: $SNAP/etc/nginx
  /var/lib/nginx:
    bind: $SNAP_DATA/var/lib/nginx
  /var/log/nginx:
    bind: $SNAP_DATA/var/log/nginx
  /usr/share/nginx/html:
    bind: $SNAP_DATA/usr/share/nginx/html

# File plugs may conflict with the layout.
plugs:
  mnt:
    interface: system-files
    write:
      - /mnt
