name: Docker Image CI

on:
  release:
    types: [prereleased, released]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Backroll core Docker image
      run: docker build ./src/core --tag dimsicloud/backroll:${{ github.event.release.tag_name }}
    - name: Build Backroll UI Docker image
      run: docker build ./src/ui --tag dimsicloud/backroll-ui:${{ github.event.release.tag_name }}

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push Backroll core image
      run: docker push dimsicloud/backroll:${{ github.event.release.tag_name }}
    - name: push Backroll UI image
      run: docker push dimsicloud/backroll-ui:${{ github.event.release.tag_name }}
