name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Backroll UI image
      run: docker build ./src/ui --file src/ui/Dockerfile --tag dimsicloud/backroll-ui:0.2.${{ github.run_number }}
    - name: Build Backroll Core image
      run: docker build ./src/core --file src/core/Dockerfile --tag dimsicloud/backroll:0.2.${{ github.run_number }}

    - name: Tag Backroll UI image to latest
      run: docker tag dimsicloud/backroll-ui:0.2.${{ github.run_number }} dimsicloud/backroll-ui:latest

    - name: Tag Backroll Core image to latest
      run: docker tag dimsicloud/backroll:0.2.${{ github.run_number }} dimsicloud/backroll:latest

    - name: Connect to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push Backroll UI image
      run: docker push dimsicloud/backroll-ui:0.2.${{ github.run_number }}
    - name: push Backroll Core image
      run: docker push dimsicloud/backroll:0.2.${{ github.run_number }}
      
    - name: push Backroll UI latest image
      run: docker push dimsicloud/backroll-ui:latest
    - name: push Backroll Core latest image
      run: docker push dimsicloud/backroll:latest
      
