name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Backroll UI image
      run: docker build ./src/ui --file src/ui/Dockerfile --tag backroll-ui:0.2.${{ github.run_number }}
    - name: Build Backroll Core image
      run: docker build ./src/core --file src/core/Dockerfile --tag backroll:0.2.${{ github.run_number }}
    - name: Connect to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push Backroll UI image
      run: docker push backroll-ui:0.2.${{ github.run_number }}
    - name: push Backroll Core image
      run: docker push backroll:0.2.${{ github.run_number }}
      
